---
# project name
project : IMDB
use_wandb : True

# dataset
dataset : IMDB

# sweep 
epochs : 10
seed : 67
optimizer : 
  method : 'sgd_torch'
  bs : 4
  lr : [0.00001,0.00003,0.0001,0.0003,0.001,0.003]
...