wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1680088547.100216
    t:
      1:
      - 1
      - 40
      - 55
      2:
      - 1
      - 40
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.8.5
      5: 0.14.0
      8:
      - 5
dataset:
  desc: null
  value: IMDB
epochs:
  desc: null
  value: 10
optimizer:
  desc: null
  value:
    bs: 4
    lr: 1.0e-05
    method: signum
project:
  desc: null
  value: IMDB
seed:
  desc: null
  value: 67
use_wandb:
  desc: null
  value: true
